# Introducción a NumPy

__NumPy__ is a _Python library_ for scientific computing. NumPy stands for Numerical Python.

- Numpy is a library used specifically for advanced and faster data manipulation in Python. 
- Numpy allows us to effectively manage and manipulate our datasets with minimal programming.
- The main benefit of NumPy is that it allows extremely fast data generation and handling. 
- NumPy has its own built-in data structure called an array that is similar to the normal Python list, but can store and operate on data much more efficiently.

Importing the library and checking the numpy version

In [1]:
import numpy as np

print(np.__version__)

1.21.5


Creating a list without numpy in the traditional python style

In [2]:
import numpy as np

some_list = [1, 2, 3, 4, 5, 6]
type(some_list)

list

## Arrays
            
- We can create 1-D, 2-D, 3-D or N-D Numpy arrays. 
- On this object, the attribute `shape` represents the dimensions.

Creating an array from a simple list

In [3]:
some_array = np.array(some_list)

display(
    type(some_array),
    some_array,
    some_array.shape,
    some_array.ndim
)

numpy.ndarray

array([1, 2, 3, 4, 5, 6])

(6,)

1

Creating an array from lists

In [4]:
some_matriz = np.array([[1, 2, 3], [4, 5, 6]])

display(
    type(some_matriz),
    some_matriz,
    some_matriz.shape,
    some_matriz.ndim
)

numpy.ndarray

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

2

Creating an 3D array from lists

In [5]:
some_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

display(
    type(some_3d),
    some_3d,
    some_3d.shape,
    some_3d.ndim
)

numpy.ndarray

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

(2, 2, 3)

3

Creating an N-Dimentions array

In [6]:
some_nd = np.array([1, 2, 3, 4], ndmin=5)

display(
    type(some_nd),
    some_nd,
    some_nd.shape,
    some_nd.ndim
)

numpy.ndarray

array([[[[[1, 2, 3, 4]]]]])

(1, 1, 1, 1, 4)

5

## Functions to populate Arrays

In [7]:
#
# Function ones()
# ===============================================
#
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [8]:
#
# Function zeros()
# ===============================================
#
ones_array = np.zeros(5)
ones_array

array([0., 0., 0., 0., 0.])

In [9]:
#
# Function arange()
# ===============================================
#
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#
# Function linspace()
# ===============================================
#
linspace_array = np.linspace(
    start=1,
    stop=5,
    num=20,
    endpoint=True,
)

linspace_array

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
#
# Using random numbers
# ===============================================
#
display(
    np.random.random(
        size=(3, 4),
    ),
    "",
    np.random.uniform(
        low=1,
        high=2,
        size=(3, 4),
    ),
    "",
    np.random.normal(
        loc=1,
        scale=2,
        size=(3, 4),
    ),
)

array([[0.73541058, 0.5544994 , 0.91764624, 0.09254991],
       [0.25536545, 0.015949  , 0.01451477, 0.81652083],
       [0.04434863, 0.03342206, 0.51707768, 0.01378952]])

''

array([[1.97630651, 1.44172446, 1.90780345, 1.43736126],
       [1.49883477, 1.14069806, 1.48776941, 1.46428511],
       [1.33137599, 1.45093633, 1.6110255 , 1.69936877]])

''

array([[ 2.43406063, -1.75987083,  2.88043065, -0.10227874],
       [ 7.02894776,  3.57506065,  0.89632731, -1.43588813],
       [ 2.37577466,  0.51483339,  2.68488829,  4.74288296]])

## Selecting elements of an array

Selecting one or a slice

In [12]:
some_array = np.arange(10)

display(
    some_array[0],
    some_array[-1],
    some_array[2:7],
)

0

9

array([2, 3, 4, 5, 6])

Selecting columns of a 2-D array

In [13]:
some_matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)
some_matrix[:,0]

array([1, 4, 7])

In [14]:
some_matrix[:,1]

array([2, 5, 8])

Selecting rows of a 2-D array

In [15]:
some_matrix[1,:]

array([4, 5, 6])

## Changing the shape of arrays

The `reshape()` Method

In [16]:
display(
    range_array.reshape(2, 5),
    '---',
    range_array.reshape(5, 2),
    '---',
    range_array.reshape(5, 2).shape,
)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

'---'

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

'---'

(5, 2)

In [17]:
#
# Función stack()
# ===============================================
#
a = np.array((1,2,3))
b = np.array((2,3,4))
ab = np.column_stack((a,b))
ab

array([[1, 2],
       [2, 3],
       [3, 4]])

## Some statistical functions

In [18]:
display(
    np.mean(range_array),
    np.median(range_array),
    np.var(range_array),
    np.std(range_array),
)

4.5

4.5

8.25

2.8722813232690143

## Arithmetic operators over arrays

In [27]:
first_array = np.random.random(4)
second_array = np.random.random(4)

display(
    first_array,
    second_array,
    first_array + second_array,
    first_array / second_array **2,
)

array([0.79323517, 0.20877097, 0.83360937, 0.27508421])

array([0.63577448, 0.79597308, 0.79891417, 0.25511472])

array([1.42900965, 1.00474405, 1.63252354, 0.53019894])

array([1.96243728, 0.32951361, 1.30605761, 4.22663376])

In [28]:
first_matrix = np.random.uniform(
    low=1,
    high=2,
    size=(3, 3),
)

second_matrix = np.random.uniform(
    low=10,
    high=11,
    size=(3, 3),
)

display(
    first_matrix,
    second_matrix,
    first_matrix - second_matrix
)

array([[1.738643  , 1.72579581, 1.1002487 ],
       [1.33708745, 1.64499526, 1.03884638],
       [1.67967974, 1.42598663, 1.61657016]])

array([[10.75146054, 10.46066928, 10.32792919],
       [10.91452128, 10.72594559, 10.86602282],
       [10.88509882, 10.22874549, 10.8603423 ]])

array([[-9.01281754, -8.73487347, -9.22768049],
       [-9.57743383, -9.08095033, -9.82717644],
       [-9.20541908, -8.80275887, -9.24377214]])

## Logical operators

In [29]:
np.arange(10) > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

## Logical selection

In [22]:
some_array = np.arange(10)
bool_array = some_array > 5
some_array[bool_array]

array([6, 7, 8, 9])

In [30]:
array_gt_3 = some_array > 3
array_lt_8 = some_array < 8
array_gt_3_and_lt_8 = np.logical_and(array_gt_3, array_lt_8)
array_gt_3_and_lt_8

array([False, False, False, False,  True,  True,  True,  True, False,
       False])

In [31]:
array_not_gt_3_or_not_lt_8 = np.logical_or(
    np.logical_not(array_gt_3), np.logical_not(array_lt_8)
)
array_not_gt_3_or_not_lt_8

array([ True,  True,  True,  True, False, False, False, False,  True,
        True])

## Iteration over arrays

In [32]:
for value in range_array:
    print(value)

0
1
2
3
4
5
6
7
8
9


iteration over 2-D arrays

In [34]:
display(first_matrix)

print('')

for value in first_matrix:
    print(value)

print('')

for value in np.nditer(first_matrix):
    print(value)

array([[1.738643  , 1.72579581, 1.1002487 ],
       [1.33708745, 1.64499526, 1.03884638],
       [1.67967974, 1.42598663, 1.61657016]])


[1.738643   1.72579581 1.1002487 ]
[1.33708745 1.64499526 1.03884638]
[1.67967974 1.42598663 1.61657016]

1.7386429996842452
1.7257958122700137
1.1002486983154074
1.3370874504127763
1.644995261097727
1.0388463767680274
1.6796797442172513
1.4259866259103022
1.6165701556827652
